// This file was auto-generated by ML.NET Model Builder. 

using System;
using Name_Entity_Recognition_Test_ProgramML.Model;

namespace Name_Entity_Recognition_Test_ProgramML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Valid = 1F,
                Text = @"Acute Exposure/ The sensory irritating potential of a series of saturated and unsaturated aliphatic and cyclic aldehydes was investigated in B6C3F1 and Swiss Webster mice.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Subject with predicted Subject from sample data...\n\n");
            Console.WriteLine($"Valid: {sampleData.Valid}");
            Console.WriteLine($"Text: {sampleData.Text}");
            Console.WriteLine($"\n\nPredicted Subject value {predictionResult.Prediction} \nPredicted Subject scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
