// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Name_Entity_Recognition_Test_ProgramML.Model
{
    public class ModelInput
    {
        [ColumnName("Subject"), LoadColumn(0)]
        public string Subject { get; set; }


        [ColumnName("Valid"), LoadColumn(1)]
        public float Valid { get; set; }


        [ColumnName("Text"), LoadColumn(2)]
        public string Text { get; set; }


    }
}
